const SETTINGS_STORAGE_KEY = "settings";
const TO_PLAY_STORAGE_KEY = "toPlay";

const NICK_SETTING_KEY = "nick";
const PASSWORD_SETTING_KEY = "password";
const INTERVAL_SETTING_KEY = "interval";
const COMPLETE_SETTING_KEY = "complete";

const FARMERSI_URL = "https://farmersi.pl/";

const RESTART_MESSAGE_PROPERTY = "restart";

export {
    SETTINGS_STORAGE_KEY,
    TO_PLAY_STORAGE_KEY,
    NICK_SETTING_KEY,
    PASSWORD_SETTING_KEY,
    INTERVAL_SETTING_KEY,
    COMPLETE_SETTING_KEY,
    FARMERSI_URL,
    RESTART_MESSAGE_PROPERTY,
};
