const STORAGE_KEY_SETTINGS = "settings";
const STORAGE_KEY_TO_PLAY = "toPlay";
const STORAGE_KEY_UNREAD_MESSAGES = "unreadMessages";
const STORAGE_KEY_TEAM_COMMENTS = "teamCommentsGames";

const SETTING_KEY_NICK = "nick";
const SETTING_KEY_PASSWORD = "password";
const SETTING_KEY_INTERVAL = "interval";
const SETTING_KEY_NOTIFY_GAME = "notifyGame";
const SETTING_KEY_NOTIFY_MESSAGE = "notifyMessage";
const SETTING_KEY_NOTIFY_COMMENT = "notifyComment";
const SETTING_KEY_COMPLETE = "complete";

const FARMERSI_URL = "https://farmersi.pl/";
const FARMERSI_NOTIFIER_API_ENDPOINT = "https://farmersi.pl/api/notifier";

const RESTART_MESSAGE_PROPERTY = "restart";

export {
    STORAGE_KEY_SETTINGS,
    STORAGE_KEY_TO_PLAY,
    STORAGE_KEY_UNREAD_MESSAGES,
    STORAGE_KEY_TEAM_COMMENTS,
    SETTING_KEY_NICK,
    SETTING_KEY_PASSWORD,
    SETTING_KEY_INTERVAL,
    SETTING_KEY_NOTIFY_GAME,
    SETTING_KEY_NOTIFY_MESSAGE,
    SETTING_KEY_NOTIFY_COMMENT,
    SETTING_KEY_COMPLETE,
    FARMERSI_URL,
    FARMERSI_NOTIFIER_API_ENDPOINT,
    RESTART_MESSAGE_PROPERTY,
};
